/**
 * Test configuration for Cloudflare Workers
 * This file provides wrangler.toml settings for testing
 */

name = "student-db-ms-test"
main = "src/index.ts"
compatibility_date = "2025-10-05"

# Test D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "student_db_test"
database_id = "test-database-id"

# Test R2 bucket binding
[[r2_buckets]]
binding = "CERT_BUCKET"
bucket_name = "student-certificates-test"

# Test KV namespace for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "test-kv-namespace-id"
preview_id = "test-kv-preview-id"

# Test KV namespace for caching
[[kv_namespaces]]
binding = "CACHE_KV"
id = "test-cache-kv-id"
preview_id = "test-cache-kv-preview-id"

# Test Durable Objects
[[durable_objects.bindings]]
name = "NOTIFICATION_MANAGER"
class_name = "NotificationManager"

# Test environment variables
[vars]
JWT_ALG = "HS256"
TOKEN_TTL_SECONDS = 3600
SENDGRID_FROM_EMAIL = "test@example.com"
SENDGRID_FROM_NAME = "Test System"
TWILIO_FROM_NUMBER = "+1234567890"
APP_BASE_URL = "https://test.example.com"
ENVIRONMENT = "test"
LOG_LEVEL = "debug"
VIRUS_SCAN_ENABLED = "false"
RATE_LIMIT_ENABLED = "true"

# Test Durable Object migrations
[[migrations]]
tag = "v1"
new_classes = ["NotificationManager"]